CREATE TABLE UDO_ADDITIONAL_CONDITION (
      ID NUMBER(17, 0) NOT NULL,
      NORM_MUNITION_ID NUMBER(17, 0) NOT NULL,
      MUNITION_ID NUMBER(17, 0) NOT NULL,
      DESCRIPTION VARCHAR2(250) NOT NULL,
      SEX NUMBER(1, 0), --пол
      DIVISION_ID NUMBER(17, 0), --подразделение
      POSITION_ID NUMBER(17, 0), --должность
      RANK_ID NUMBER(17, 0), --звание
      CLIMATE VARCHAR(100), --климат
      REPLACE_MUNITION_ID NUMBER(17, 0), --имущество (если требуется замена)
      CONSTRAINT ADDITIONAL_CONDITION_ID_PK PRIMARY KEY (id)
)

CREATE TABLE UDO_DIVISION (
      ID NUMBER(17, 0) NOT NULL,
      NAME VARCHAR2(50) NOT NULL,
      DESCRIPTION VARCHAR2(100),
      CONSTRAINT DIVISION_ID_PK PRIMARY KEY (id),
      CONSTRAINT DIVISION_UNIQUE UNIQUE (name)
)

CREATE TABLE UDO_RANK (
      ID NUMBER(17, 0) NOT NULL,
      NAME VARCHAR2(50) NOT NULL,
      DESCRIPTION VARCHAR2(100),
      CONSTRAINT RANK_ID_PK PRIMARY KEY (id),
      CONSTRAINT RANK_UNIQUE UNIQUE (name)
)

CREATE TABLE UDO_POSITION (
      ID NUMBER(17, 0) NOT NULL,
      NAME VARCHAR2(50) NOT NULL,
      DESCRIPTION VARCHAR2(100),
      CONSTRAINT POSITION_ID_PK PRIMARY KEY (id),
      CONSTRAINT POSITION_UNIQUE UNIQUE (name)
)

CREATE TABLE UDO_PERSONAL_CARD (
    ID             NUMBER(17) NOT NULL,
    FIO            VARCHAR2(80),
    JOB_BEGIN_DATE DATE,
    SEX            NUMBER(1),
    DIVISION_ID    NUMBER(17),
    POSITION_ID    NUMBER(17),
    RANK_ID        NUMBER(17),
    CLIMATE        VARCHAR2(100),
    CONSTRAINT UDO_PERSONAL_CARD_PK PRIMARY KEY (ID),
    CONSTRAINT UDO_PERSONAL_CARD_DIVISION_FK FOREIGN KEY (DIVISION_ID),
    CONSTRAINT UDO_PERSONAL_CARD_POSITION_FK FOREIGN KEY (POSITION_ID),
    CONSTRAINT UDO_PERSONAL_CARD_RANK_FK FOREIGN KEY (RANK_ID)
)

CREATE TABLE UDO_PERSONAL_CARD_NORM (
    ID         NUMBER(17) NOT NULL,
    LKART_ID   NUMBER(17) NOT NULL,
    NORM_ID    NUMBER(17) NOT NULL,
    BEGIN_DATE DATE,
    END_DATE   DATE,
    CONSTRAINT UDO_PERSONAL_CARD_NORM_PK PRIMARY KEY (ID)
)

select a.*
from udo_personal_card c,
     udo_personal_card_norm n,
     udo_additional_condition a
where c.id = n.lkart_id
  and n.norm_id = a.norm_munition_id
  and ( c.division_id = a.division_id or a.division_id is null )
  and ( c.position_id = a.position_id  or  a.position_id is null  )
  and ( c.rank_id = a.rank_id  or  a.rank_id is null  )
  and ( c.climate = a.climate  or  a.climate is null  )